name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fix Git ownership
        run: git config --global --add safe.directory /github/workspace
      - name: Build and deploy
        run: |
          npm install
          npm run build
          npm run custom-deploy
